-- 🌾 농사 도움 시드(D-027, 2026-08-28) — 라이브 적용 완료본의 보존 사본(재검수 P1-1).
-- 원칙: 일반적 공공 안전·기술 지식 수준만(의학·법률 조언 금지), 출처 필수,
-- verified_at=null(운영자 검수 후 갱신 — D-026과 동일 절차).
-- 키 구조: {ko:{name,description},en:{name,description}} — life_info와 동일(localizedContent 헬퍼 공용).
-- 안전 문구 수정 시 이 파일을 함께 갱신할 것(변경 이력 = 이 파일의 git diff).

insert into public.farm_tips (crop_type, localized_content, source_url, verified_at, is_published) values
(null, '{"ko":{"name":"폭염 속 밭일, 3가지만 기억하세요","description":"물·그늘·휴식이 기본입니다. 목이 마르기 전에 물을 자주 마시고, 가장 더운 시간(오후 2~5시)에는 무리한 작업을 피하세요. 어지럽거나 메스꺼우면 바로 그늘에서 쉬고, 심하면 119에 전화하세요."},"en":{"name":"Working in extreme heat: remember 3 things","description":"Water, shade, rest. Drink water often before you feel thirsty, and avoid heavy work during the hottest hours (2–5 PM). If you feel dizzy or sick, rest in the shade right away — call 119 if it gets worse."}}', 'https://www.nongsaro.go.kr/', null, true),
(null, '{"ko":{"name":"농약 살포할 때 꼭 지킬 것","description":"마스크·장갑·긴옷 등 보호구를 착용하고, 바람을 등지고 뿌리세요. 살포 후에는 비누로 손과 얼굴을 씻고 옷을 갈아입으세요. 농약 병은 다른 용도로 절대 재사용하지 마세요. 몸이 이상하면 즉시 병원에 가세요."},"en":{"name":"Spraying pesticides safely","description":"Wear a mask, gloves and long clothing, and spray with the wind at your back. Wash your hands and face with soap and change clothes afterward. Never reuse pesticide bottles for anything else. If you feel unwell, see a doctor right away."}}', 'https://psis.rda.go.kr/', null, true),
(null, '{"ko":{"name":"경운기·트랙터 사고를 피하려면","description":"출발 전 브레이크와 타이어를 확인하세요. 경사진 길과 좁은 농로에서는 속도를 줄이고, 사람을 짐칸에 태우지 마세요. 해 진 뒤에는 반사판과 등화 장치가 잘 보이는지 확인하세요."},"en":{"name":"Avoiding tiller and tractor accidents","description":"Check brakes and tires before starting. Slow down on slopes and narrow farm roads, and never carry people in the cargo area. After dark, make sure reflectors and lights are clearly visible."}}', 'https://www.rda.go.kr/', null, true),
(null, '{"ko":{"name":"겨울 비닐하우스, 환기가 생명입니다","description":"난방기를 쓰는 하우스 안에서는 일산화탄소가 쌓일 수 있습니다. 머리가 아프거나 어지러우면 바로 밖으로 나와 환기하세요. 밀폐된 하우스 안에서 잠들지 마세요."},"en":{"name":"Winter greenhouses: ventilation saves lives","description":"Carbon monoxide can build up in heated greenhouses. If you get a headache or feel dizzy, go outside and ventilate immediately. Never sleep inside a closed greenhouse."}}', 'https://www.nongsaro.go.kr/', null, true),
(null, '{"ko":{"name":"허리를 지키는 농작업 습관","description":"쪼그려 앉는 작업은 30분마다 일어나 허리를 펴 주세요. 무거운 것은 허리가 아니라 다리 힘으로 들고, 두 사람이 나눠 드세요. 작업 전후 1~2분 스트레칭이 통증을 크게 줄입니다."},"en":{"name":"Protect your back while farming","description":"When working crouched, stand up and stretch every 30 minutes. Lift heavy loads with your legs, not your back — and share the load with another person. One or two minutes of stretching before and after work greatly reduces pain."}}', 'https://www.nongsaro.go.kr/', null, true),
('딸기', '{"ko":{"name":"딸기 하우스 관리의 기본","description":"딸기는 온도와 습도에 민감합니다. 낮과 밤의 온도 차, 물 주는 시간을 농장 관리자와 확인하고 기록해 두면 좋습니다. 잎에 반점이나 벌레가 보이면 사진을 찍어 관리자에게 바로 알려 주세요. 작목별 자세한 기술은 농사로에서 볼 수 있습니다."},"en":{"name":"Strawberry greenhouse basics","description":"Strawberries are sensitive to temperature and humidity. Check day/night temperature ranges and watering schedules with your farm manager. If you see spots or insects on leaves, take a photo and tell the manager right away. Detailed crop guides are on Nongsaro."}}', 'https://www.nongsaro.go.kr/', null, true),
('사과', '{"ko":{"name":"사과밭 작업, 계절마다 다릅니다","description":"봄에는 꽃과 열매 솎기(적화·적과), 여름에는 가지 정리, 가을에는 수확이 중심입니다. 사다리 작업은 바닥이 평평한지 꼭 확인하고, 혼자보다는 둘이 함께 하세요. 작목별 자세한 기술은 농사로에서 볼 수 있습니다."},"en":{"name":"Apple orchard work changes by season","description":"Spring is for thinning flowers and fruit, summer for pruning, autumn for harvest. When using a ladder, always check the ground is level and work in pairs. Detailed crop guides are on Nongsaro."}}', 'https://www.nongsaro.go.kr/', null, true),
(null, '{"ko":{"name":"이번 주 농사 정보가 궁금하다면","description":"농촌진흥청 농사로에서는 매주 시기별 농사 정보(주간농사정보)와 1분 농업 영상을 무료로 제공합니다. 병해충 발생 정보도 볼 수 있어요. 한국어가 어렵다면 번역 앱과 함께 보거나 이웃에게 물어보세요."},"en":{"name":"Weekly farming info","description":"Nongsaro (Rural Development Administration) publishes free weekly farming info and 1-minute farming videos, plus pest outbreak alerts. If Korean is difficult, use a translation app or ask a neighbor on this app."}}', 'https://www.nongsaro.go.kr/', null, true);
